// Auto-generated by scripts/bundle-translations.ts
// Do not edit manually.

export const FALLBACK_LOCALE = "en" as const;

export const FALLBACK_BLOG = {
  "indexPageTitle": "Blog",
  "newsletter": {
    "title": "Stay Updated",
    "description": "Get the latest EdgeKits news directly to your inbox.",
    "placeholder": "Enter your email",
    "button": "Subscribe",
    "success": "Thanks for subscribing!",
    "validation": {
      "invalidEmail": "Please enter a valid email address."
    }
  },
  "ui": {
    "readMore": "Read more",
    "backToOverview": "Back to Overview",
    "publishedOn": "Published on",
    "readTime": "{min} min read"
  },
  "counter": {
    "title": "Counter demo",
    "increment": "Increment",
    "reset": "Reset",
    "patterns": {
      "zero": "No items",
      "one": "{count} item",
      "other": "{count} items"
    }
  }
} as const;

export const FALLBACK_COMMON = {
  "nav": {
    "home": "Astro components & islands",
    "blog": "Markdown i18n examples",
    "mobileButton": "Menu"
  },
  "footer": {
    "license": "Under the MIT license."
  },
  "notFound": {
    "title": "404 — Page not found",
    "message": "The page you are looking for does not exist or has been moved.",
    "backToHome": "Go back to homepage"
  }
} as const;

export const FALLBACK_LANDING = {
  "seo": {
    "title": "Zero-JS i18n Astro Starter for Cloudflare Workers",
    "description": "Ship multilingual apps faster without hydration bloat. Full integration with Cloudflare Workers & KV, automated TypeScript generation, and edge caching out of the box."
  },
  "hero": {
    "title": "Astro Component Demo",
    "subtitle": "A high-performance <strong>Astro 5.0 + Cloudflare Workers</strong> template featuring an <strong>Edge-Native Internationalization Engine</strong> with a <strong>0 KB client bundle</strong>.",
    "description": "Unlike traditional setups that ship heavy JSON dictionaries to the client, this architecture stores translations in <strong>Cloudflare KV</strong>, fetches only the locale required by the user or browser, loads only the specific namespaces needed for each page or component via a <strong>single batch request</strong>, and serves <strong>pre-rendered HTML</strong>, which is cached to reduce KV requests.",
    "cta": "Explore the Blog"
  },
  "features": {
    "title": "The cards below are the React Islands",
    "feature1Title": "Edge-Loaded Translations",
    "feature1Desc": "Translations are fetched at the edge in a single KV batch request, with 0 KB client bundle and sub-10ms access to the exact locale and namespaces required for the page.",
    "feature2Title": "Dynamic Locale Resolution",
    "feature2Desc": "No duplicated pages like /en/about.astro, /es/about.astro, etc. Locales and translation namespaces are resolved dynamically per request, keeping routing clean and the project easy to maintain.",
    "feature3Title": "Strictly Typed Translations",
    "feature3Desc": "Translation types are auto-generated from your src/locales JSON files, ensuring a fully type-safe i18n schema across Astro and React Islands — with built-in IntelliSense and compile-time guarantees."
  },
  "builtWith": {
    "title": "Built With",
    "subtitle": "Edge-native stack combining Astro, React Islands, Cloudflare Workers & KV, Tailwind CSS, and Shadcn/ui."
  }
} as const;
