// Auto-generated by scripts/bundle-translations.ts
// Do not edit manually.

export const NAMESPACE_KEYS = [
  'blog',
  'common',
  'counter',
  'landing',
  'messages',
  'newsletter',
] as [string, ...string[]]

export const LOCALES_WITH_TRANSLATIONS = [
  'de',
  'en',
  'es',
  'ja',
  'pt-br',
] as const

export const FULLY_TRANSLATED_LOCALES = [
  'de',
  'en',
  'es',
  'ja',
  'pt-br',
] as const

/**
 * Monotonic translation bundle version.
 * Updated on every `npm run i18n:bundle` run.
 */
export const TRANSLATIONS_VERSION = '07d226bb5139'
