// Auto-generated by scripts/bundle-translations.ts
// Do not edit manually.

export const NAMESPACE_KEYS = [
  'blog',
  'common',
  'counter',
  'landing',
  'messages',
  'newsletter',
] as [string, ...string[]]

export const LOCALES_WITH_TRANSLATIONS = ['de', 'en', 'es', 'ja'] as const

export const FULLY_TRANSLATED_LOCALES = ['de', 'en', 'es', 'ja'] as const

/**
 * Monotonic translation bundle version.
 * Updated on every `npm run i18n:bundle` run.
 */
export const TRANSLATIONS_VERSION = '0472d052ff99'
